### ISSUE TITLE
Search seems to be case sensitive

### ISSUE THREAD

**Issue by larsenpedersen** [sketchpacks/sketchpacks.com#10]
The search functionality seems to be case sensitive - is this on purpose?

Because of that, ios, Ios iOS and IOS results in four different searches :)

**Comment by adamkirkwood** [comment]
@larsenpedersen I plan on improving the search, primarily because of issue you are mentioning. I think I may leverage something like ElasticSearch to handle this work.

I'll make sure to keep this issue updated on its progress.

**Comment by adamkirkwood** [comment]
@larsenpedersen Searches are now performed as case-insensitive. I've created a [review app](https://sketchpacks-staging-pr-11.herokuapp.com/) that has the search improvement. Please feel free to let me know what you think.
