### ISSUE TITLE
Site is too wide on desktop in Safari

### ISSUE THREAD

**Issue by corygibbons** [sketchpacks/sketchpacks.com#6]
Works great in Chrome but something is going wrong with the home/plugins pages in Safari.

http://files.corygibbons.com/sketchpacks-bug.mov

**Comment by adamkirkwood** [comment]
@corygibbons Thanks for bringing this to my attention!

**Comment by corygibbons** [comment]
@adamkirkwood Not a problem and I look forward to seeing this project progress :smile:

**Comment by adamkirkwood** [comment]
@corygibbons Thanks for the support! I hope to continue progress on this project.
